Modal alert will be displayed if the user tries to start a new game #43
chingu-voyages/v44-tier1-team-05 pull request #98
Opened 2023-05-25 19:25 UTC by nazgul7d

hey guys,
I wrote a function for Modal alert
Please let me know if you have any comments

2023-05-25 19:41 UTC, goodman2814 approved these changes
looks good to me!

2023-05-25 23:11 UTC, PaulaR-05 requested changes
Naz! Great job!

I really like your code and also the way you built the logic behind it.
What do you think? 

thanks a lot for all your work :)

My only suggestion is to change that part of the code:
**const occupiedSquares = document.querySelectorAll(".occupied");** 
to
**const occupiedSquares = document.querySelectorAll(".block");**



Because i believe it would be more intresting if the user had submited his answer on the grid.

2023-05-25 23:16 UTC, PaulaR-05 commented on app.js
> +  const occupiedSquares = document.querySelectorAll(".occupied");
const occupiedSquares = document.querySelectorAll(".block");

it's the only part I would change, the function is really great :)

2023-05-26 16:45 UTC, PaulaR-05 approved these changes
Thanks a lot, Naz! Great Job

2023-05-26 16:45 UTC, merged